const material = (categoryKey, key, label, unit, brickyMin, brickyMax, options = {}) => ({
  key: `${categoryKey}.${key}`,
  categoryKey,
  label,
  unit,
  brickyMin,
  brickyMax,
  currency: "EUR",
  ...options,
});

export const MATERIAL_PRICE_INDEX_VERSION = "2026-v0.1";

export const MATERIAL_PRICE_INDEX = [
  // ВиК
  material("vik", "ppr_pipes", "PPR тръби", "3m_piece", 4, 8),
  material("vik", "pvc_pipes", "PVC канализационни тръби", "2m_piece", 2, 8),
  material("vik", "fittings", "Фитинги", "item", 0.5, 3),
  material("vik", "elbows", "Колена", "item", 1, 6),
  material("vik", "couplings", "Муфи", "item", 1, 4),
  material("vik", "tees", "Тетки", "item", 0.5, 5),
  material("vik", "nipples", "Нипели", "item", 1, 4),
  material("vik", "reducers", "Редукции", "item", 1, 5),
  material("vik", "clamps", "Скоби", "item", 0.5, 2),
  material("vik", "seals", "Уплътнения", "item_or_set", 1, 5),
  material("vik", "teflon_tape", "Тефлонова лента", "item", 1, 2),
  material("vik", "hemp_paste", "Кълчища / паста", "item", 2, 8),
  material("vik", "silicone", "Силикон", "cartridge", 3, 12),
  material("vik", "soft_connections", "Меки връзки", "item", 3, 12),
  material("vik", "siphon", "Сифон", "item", 5, 35),
  material("vik", "valves", "Клапани", "item", 3, 20),
  material("vik", "stop_valves", "Спирателни кранове", "item", 5, 20),
  material("vik", "cistern_float", "Поплавък за казанче", "item", 5, 15),
  material("vik", "cistern_mechanism", "Механизъм за казанче", "item", 6, 25),
  material("vik", "drain_hose", "Дренажен маркуч", "meter_or_item", 1, 8),
  material("vik", "fasteners", "Крепежи", "set", 2, 10),

  // Електро
  material("electro", "cable", "Кабел", "meter", 0.5, 3),
  material("electro", "conduit", "Гофрирана тръба", "meter", 0.5, 2),
  material("electro", "cable_channel", "Кабелен канал", "meter_or_item", 1, 6),
  material("electro", "socket_box", "Конзолна кутия", "item", 0.5, 2),
  material("electro", "junction_box", "Разклонителна кутия", "item", 1, 6),
  material("electro", "terminals", "Клеми", "item_or_set", 0.5, 5),
  material("electro", "wago", "WAGO клеми", "item_or_set", 0.5, 10),
  material("electro", "insulation_tape", "Изолирбанд", "item", 1, 4),
  material("electro", "heat_shrink", "Термосвиваем шлаух", "set_or_meter", 2, 10),
  material("electro", "socket", "Контакт", "item", 3, 20),
  material("electro", "switch", "Ключ", "item", 3, 20),
  material("electro", "frame", "Рамка", "item", 1, 10),
  material("electro", "breaker", "Автоматичен предпазител", "item", 3, 8),
  material("electro", "rcd", "ДТЗ", "item", 25, 80),
  material("electro", "busbar", "Шина", "item_or_set", 3, 15),
  material("electro", "panel_box", "Електрическо табло / кутия", "item", 10, 80),
  material("electro", "cable_lugs", "Кабелни обувки", "set", 2, 10),
  material("electro", "fasteners", "Крепежи", "set", 2, 15),

  // Боядисване
  material("painting", "latex", "Латекс", "10l_bucket", 25, 90),
  material("painting", "primer", "Грунд", "5_10l_container", 8, 35),
  material("painting", "ceiling_paint", "Боя за таван", "10l_bucket", 20, 70),
  material("painting", "masking_tape", "Тиксо", "roll", 1, 6),
  material("painting", "covering_nylon", "Покривен найлон", "pack", 1, 5),
  material("painting", "covering_film", "Покривно фолио", "pack", 2, 10),
  material("painting", "sandpaper", "Шкурка", "sheet_or_pack", 1, 8),
  material("painting", "rollers", "Валяци", "item", 2, 15),
  material("painting", "brushes", "Четки", "item", 1, 10),
  material("painting", "trays", "Ванички", "item", 2, 8),
  material("painting", "repair_mix", "Малка поправъчна смес", "pack", 3, 15),
  material("painting", "mold_treatment", "Препарат против мухъл", "item", 4, 15),

  // Шпакловка и мазилки
  material("plaster", "fine_putty", "Фина шпакловка", "20_25kg_bag", 5, 18),
  material("plaster", "gypsum_putty", "Гипсова шпакловка", "20_30kg_bag", 5, 15),
  material("plaster", "cement_putty", "Циментова шпакловка", "20_25kg_bag", 6, 18),
  material("plaster", "primer", "Грунд", "5_10l_container", 8, 35),
  material("plaster", "mesh", "Мрежа", "m2", 0.5, 2),
  material("plaster", "fiberglass_tape", "Стъклофибърна лента", "roll", 2, 8),
  material("plaster", "paper_tape", "Хартиена лента", "roll", 2, 8),
  material("plaster", "corner_bead", "Ъглопротектор", "item", 1, 5),
  material("plaster", "sandpaper", "Шкурка", "sheet_or_pack", 1, 8),
  material("plaster", "plaster_mix", "Мазилка", "25_30kg_bag", 7, 30),
  material("plaster", "repair_mix", "Ремонтна смес", "5_25kg_bag", 4, 20),
  material("plaster", "mesh_adhesive", "Лепило за мрежа", "25kg_bag", 6, 18),

  // Плочки
  material("tiles", "adhesive", "Лепило за плочки", "25kg_bag", 5, 12),
  material("tiles", "flex_adhesive", "Flex лепило", "25kg_bag", 11, 20),
  material("tiles", "grout", "Фугираща смес", "1_5kg_pack", 3, 18),
  material("tiles", "primer", "Грунд", "5_10l_container", 8, 40),
  material("tiles", "waterproofing", "Хидроизолация", "5_15kg_pack", 25, 95),
  material("tiles", "wedges", "Клинове", "pack", 2, 10),
  material("tiles", "spacers", "Кръстчета", "pack", 1, 5),
  material("tiles", "leveling_system", "Нивелираща система", "set", 10, 40),
  material("tiles", "silicone", "Силикон", "cartridge", 3, 12),
  material("tiles", "profiles", "Профили", "2_5m_item", 3, 20),
  material("tiles", "trim", "Лайсни", "2_5m_item", 3, 20),
  material("tiles", "consumables", "Дребни консумативи", "set", 5, 20),

  // Баня
  material("bathroom_renovation", "ppr_pipes", "PPR тръби", "3m_piece", 4, 8),
  material("bathroom_renovation", "pvc_pipes", "PVC тръби", "2m_piece", 2, 8),
  material("bathroom_renovation", "fittings", "Фитинги", "item", 0.5, 3),
  material("bathroom_renovation", "stop_valves", "Спирателни кранове", "item", 5, 20),
  material("bathroom_renovation", "siphon", "Сифон", "item", 5, 35),
  material("bathroom_renovation", "adhesive", "Лепило за плочки", "25kg_bag", 5, 12),
  material("bathroom_renovation", "grout", "Фугираща смес", "1_5kg_pack", 3, 18),
  material("bathroom_renovation", "primer", "Грунд", "5_10l_container", 8, 40),
  material("bathroom_renovation", "waterproofing", "Хидроизолация", "5_15kg_pack", 25, 95),
  material("bathroom_renovation", "waterproofing_tape", "Хидроизолационна лента", "roll", 10, 35),
  material("bathroom_renovation", "silicone", "Силикон", "cartridge", 3, 12),
  material("bathroom_renovation", "foam", "Монтажна пяна", "cartridge", 4, 12),
  material("bathroom_renovation", "fasteners", "Крепежи", "set", 2, 15),

  // Гипсокартон
  material("drywall", "board", "Гипсокартонена плоскост", "m2", 3, 6),
  material("drywall", "moisture_board", "Влагоустойчив гипсокартон", "m2", 5, 9),
  material("drywall", "fire_board", "Пожароустойчив гипсокартон", "m2", 6, 12),
  material("drywall", "cd_profile", "CD профил", "item", 4, 11),
  material("drywall", "ud_profile", "UD профил", "item", 3, 8),
  material("drywall", "cw_profile", "CW профил", "item", 5, 12),
  material("drywall", "uw_profile", "UW профил", "item", 4, 10),
  material("drywall", "hangers", "Окачвачи", "item", 0.5, 2),
  material("drywall", "screws", "Винтове", "pack", 3, 15),
  material("drywall", "joint_tape", "Лента за фуги", "roll", 2, 10),
  material("drywall", "joint_putty", "Шпакловка за фуги", "5_25kg_pack", 5, 20),
  material("drywall", "corner_bead", "Ъглопротектор", "item", 1, 5),
  material("drywall", "mineral_wool", "Минерална вата", "m2", 2, 6),
  material("drywall", "stone_wool", "Каменна вата", "m2", 3, 10),
  material("drywall", "access_panel", "Ревизионен отвор", "item", 15, 50),

  // Подови настилки
  material("flooring", "laminate", "Ламинат", "m2", 8, 25, { isMainProduct: true }),
  material("flooring", "parquet", "Паркет", "m2", 25, 100, { isMainProduct: true }),
  material("flooring", "vinyl", "Винил", "m2", 12, 35, { isMainProduct: true }),
  material("flooring", "spc", "SPC настилка", "m2", 18, 35, { isMainProduct: true }),
  material("flooring", "underlay", "Подложка", "m2", 0.5, 5),
  material("flooring", "vapor_barrier", "Пароизолационно фолио", "m2", 0.5, 2),
  material("flooring", "skirting", "Перваз", "2_4m_item", 3, 16),
  material("flooring", "trim", "Лайсна", "item", 3, 20),
  material("flooring", "parquet_adhesive", "Лепило за паркет", "kg_or_bucket", 10, 70),
  material("flooring", "self_leveling", "Саморазливна замазка", "25kg_bag", 8, 20),
  material("flooring", "cement_screed", "Циментова замазка", "25kg_bag", 4, 10),
  material("flooring", "primer", "Грунд за под", "5_10l_container", 8, 35),

  // Климатици
  material("heating_cooling", "copper_pipe", "Медни тръби", "meter", 3.5, 12),
  material("heating_cooling", "pipe_route", "Тръбен път", "meter", 10, 25),
  material("heating_cooling", "pipe_insulation", "Изолация за тръби", "meter", 0.5, 3),
  material("heating_cooling", "brackets", "Конзоли", "set", 10, 35),
  material("heating_cooling", "drain_hose", "Дренажен маркуч", "meter", 0.5, 2),
  material("heating_cooling", "cable", "Кабел", "meter", 0.5, 3),
  material("heating_cooling", "bandage", "Бандаж", "roll", 3, 10),
  material("heating_cooling", "refrigerant", "Фреон при нужда", "partial_charge", 30, 80),
  material("heating_cooling", "pvc_channel", "PVC канал", "meter", 2, 8),
  material("heating_cooling", "fasteners", "Крепежи", "set", 2, 15),

  // Врати и дограма
  material("windows_doors", "foam", "Монтажна пяна", "cartridge", 4, 12),
  material("windows_doors", "silicone", "Силикон", "cartridge", 3, 12),
  material("windows_doors", "acrylic", "Акрил", "cartridge", 2, 8),
  material("windows_doors", "anchors", "Анкери", "pack", 3, 20),
  material("windows_doors", "brackets", "Планки", "item", 1, 10),
  material("windows_doors", "seals", "Уплътнения", "meter_or_set", 2, 20),
  material("windows_doors", "hinges", "Панти", "item_or_set", 3, 30),
  material("windows_doors", "lock", "Брава", "item", 8, 60),
  material("windows_doors", "handles", "Дръжки", "set", 8, 70),
  material("windows_doors", "hardware", "Обков", "set", 10, 150),
  material("windows_doors", "trim", "Первази / лайсни", "item_or_meter", 3, 20),

  // Мебели и монтаж
  material("furniture_mounting", "anchors", "Анкери", "pack", 3, 20),
  material("furniture_mounting", "brackets", "Планки", "item", 1, 10),
  material("furniture_mounting", "angles", "Ъгли", "item_or_set", 1, 10),
  material("furniture_mounting", "consoles", "Конзоли", "item_or_set", 3, 30),
  material("furniture_mounting", "silicone", "Силикон", "cartridge", 3, 12),
  material("furniture_mounting", "mounting_adhesive", "Монтажно лепило", "cartridge", 4, 15),
  material("furniture_mounting", "fasteners", "Крепежи", "set", 2, 15),
  material("furniture_mounting", "hinges", "Мебелни панти", "item_or_set", 2, 20),
  material("furniture_mounting", "handles", "Дръжки", "item_or_set", 2, 30),
  material("furniture_mounting", "mechanisms", "Мебелни механизми", "item_or_set", 5, 80),

  // Покриви
  material("roof_waterproofing", "roof_tiles", "Керемиди", "m2", 6, 25, { isMainProduct: true }),
  material("roof_waterproofing", "ridge_tiles", "Капаци", "item", 2, 10),
  material("roof_waterproofing", "battens", "Летви", "meter_or_item", 1, 5),
  material("roof_waterproofing", "roof_membrane", "Покривно фолио", "m2", 0.5, 3),
  material("roof_waterproofing", "bitumen_membrane", "Битумна мембрана", "10m2_roll", 26, 60),
  material("roof_waterproofing", "liquid_waterproofing", "Течна хидроизолация", "5_20kg_pack", 25, 100),
  material("roof_waterproofing", "primer", "Грунд", "5_10l_container", 8, 40),
  material("roof_waterproofing", "sheet_metal", "Ламарина", "m2_or_sheet", 10, 40),
  material("roof_waterproofing", "gutters", "Улуци", "meter", 5, 20),
  material("roof_waterproofing", "downpipes", "Водостоци", "meter", 5, 20),
  material("roof_waterproofing", "sealant", "Полиуретанов уплътнител", "cartridge", 5, 15),
  material("roof_waterproofing", "drainage", "Дренажни елементи", "item", 5, 40),
  material("roof_waterproofing", "funnels", "Воронки", "item", 15, 60),

  // Общи консумативи и логистика
  material("common", "dowels", "Дюбели", "pack", 1, 8),
  material("common", "screws", "Винтове", "pack", 1, 10),
  material("common", "anchors", "Анкери", "pack", 3, 20),
  material("common", "fasteners", "Крепежи", "set", 2, 15),
  material("common", "silicone", "Силикон", "cartridge", 3, 12),
  material("common", "acrylic", "Акрил", "cartridge", 2, 8),
  material("common", "foam", "Монтажна пяна", "cartridge", 4, 12),
  material("common", "mounting_adhesive", "Монтажно лепило", "cartridge", 4, 15),
  material("common", "bags", "Чували", "pack", 2, 10),
  material("common", "big_bag", "Big bag", "item", 5, 20),
  material("common", "container", "Контейнер", "trip", 80, 150),
  material("common", "transport", "Транспорт", "trip", 40, 120),
  material("common", "landfill_fee", "Такса сметище", "quantity", 10, 80),
  material("common", "protective_consumables", "Защитни консумативи", "set", 5, 30),
  material("common", "cleaning_consumables", "Почистващи консумативи", "set", 5, 30),
];

const MATERIALS_BY_KEY = new Map(MATERIAL_PRICE_INDEX.map((item) => [item.key, item]));

export function getMaterialPriceItem(key) {
  return MATERIALS_BY_KEY.get(key) || null;
}

export function getMaterialPriceItems(keys = []) {
  return keys.map(getMaterialPriceItem).filter(Boolean);
}
